version: '3'
services:
  postgres_test:
    container_name: postgres_test
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    image: postgres:16.0-alpine

  
  